on:
  push:
    branches:
    - main
    - release/*
  workflow_dispatch:
    
jobs:
  my_job:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    
    steps:
    - name: npm install
      run: |
        npm install
